### ISSUE TITLE
Description of the grid types

### ISSUE THREAD

**Issue by jarethholt** [ecmwf/eccodes-python#4]
I have a grib file with this grid specified:

    gridDefinitionTemplateNumber = 50;
    J = 639;
    K = 639;
    M = 639;
    gridType = sh;
    NV = 276;

From searching, I see that `sh` is a recognized grid that comes up in examples of allowed gridTypes, but I can't find any description of what that grid is. Despite being a known gridType, I can't get any of the grib tools to display lat/lon values. Can someone point me to what this grid is and how it should be used?

I am posting this here 1) because I plan to primarily use the Python tools, and 2) eccodes has no issues page.

**Comment by alexamici** [comment]
@jarethholt `sh` is the "spherical harmonics" grid type see for example: https://confluence.ecmwf.int/display/FCST/Spectral+representation+of+the+IFS . I don't know much about it myself and I think data cannot get the latitude/longitude of eveery point because `sh` is not a projection.

I'll close this issue as it is a question about GRIB format, not really *cfgrib* and not even *ecCodes*.
